# Generated by Django 2.1 on 2019-09-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=128, null=True, upload_to='users/%Y/%m/%d/', verbose_name='头像'),
        ),
    ]
