# Generated by Django 2.1 on 2019-09-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='idc',
        ),
    ]
