# Generated by Django 2.1 on 2019-09-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_remove_asset_idc'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server', to='cmdb.Asset', verbose_name='资产'),
        ),
    ]
