# Generated by Django 2.1.5 on 2019-09-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbsqlite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='email',
            field=models.CharField(max_length=128, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
