# Generated by Django 2.1.5 on 2019-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbsqlite', '0002_auto_20190929_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
