# Generated by Django 2.1.5 on 2019-09-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbsqlite', '0003_auto_20190929_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleprofile',
            name='hits',
            field=models.IntegerField(default=0, verbose_name='点击热度'),
        ),
    ]
